import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const root = process.cwd();
const questionsPath = path.join(root, 'templates', 'intake-questions.json');
const answersPath = path.join(root, '.agent-sdlc', 'project.answers.json');
const statusPath = path.join(root, '.agent-sdlc', 'governance-status.json');
const templatesDir = path.join(root, 'templates', 'docs');
const outputDir = path.join(root, 'docs', 'governance');
const appDir = path.join(root, 'app');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function hasValue(value) {
  return typeof value === 'string' && value.trim().length > 0;
}

function normalise(value) {
  return value.trim();
}

function writeFileIfMissing(file, content) {
  if (fs.existsSync(file)) return false;
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content);
  return true;
}

function projectSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'agent-project';
}

function createProjectScaffold(answers) {
  const slug = projectSlug(answers.PROJECT_NAME);
  const scaffoldFiles = new Map([
    [
      path.join(appDir, 'README.md'),
      `# ${answers.PROJECT_NAME}

Local front-end demo workspace generated by the AI-Agent SDLC intake.

## Scope

- Build an interactive recruitment maps demo using fictional public sample data only.
- Keep visual map content accessible with text and table alternatives.
- Do not use paid map APIs, backend services, secrets, production systems, real client data, real candidate data or personal data.

## Structure

\`\`\`text
app/
  index.html
  src/
    main.js
    styles.css
    data/
      fictional-recruitment-map-data.js
    features/
      recruitment-map/
        controller.js
        view.js
    lib/
      dom.js
  tests/
    accessibility-checklist.md
    manual-test-plan.md
  docs/
    agent-handoff.md
    implementation-notes.md
    review-evidence.md
\`\`\`

## Agent Rules

- Run \`npm run governance:check\` before implementation work.
- Record meaningful work with \`npm run audit:new\`.
- Keep implementation inside this approved local demo scope.
`
    ],
    [
      path.join(appDir, 'index.html'),
      `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${answers.PROJECT_NAME}</title>
    <link rel="stylesheet" href="./src/styles.css">
  </head>
  <body>
    <main id="app" class="app-shell">
      <section class="empty-state" aria-labelledby="project-title">
        <p class="kicker">Fictional public demo data only</p>
        <h1 id="project-title">${answers.PROJECT_NAME}</h1>
        <p>This scaffold is ready for a governed local recruitment maps demo implementation.</p>
      </section>
    </main>
    <script type="module" src="./src/main.js"></script>
  </body>
</html>
`
    ],
    [
      path.join(appDir, 'src', 'main.js'),
      `import { fictionalRecruitmentMapData } from './data/fictional-recruitment-map-data.js';
import { createRecruitmentMapView } from './features/recruitment-map/view.js';
import { createRecruitmentMapController } from './features/recruitment-map/controller.js';

const root = document.querySelector('#app');

if (root) {
  const view = createRecruitmentMapView(root);
  const controller = createRecruitmentMapController({
    data: fictionalRecruitmentMapData,
    view
  });

  controller.init();
}
`
    ],
    [
      path.join(appDir, 'src', 'styles.css'),
      `:root {
  color-scheme: light;
  --ink: #1d2733;
  --muted: #5d6978;
  --surface: #f6f1e8;
  --panel: #ffffff;
  --line: #d7d0c5;
  --accent: #146c5c;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  color: var(--ink);
  background: var(--surface);
  font-family: Avenir Next, Avenir, Segoe UI, sans-serif;
}

.app-shell {
  min-height: 100vh;
  padding: clamp(1rem, 3vw, 3rem);
}

.empty-state {
  max-width: 56rem;
  padding: clamp(1.5rem, 4vw, 4rem) 0;
}

.kicker {
  margin: 0 0 0.75rem;
  color: var(--accent);
  font-size: 0.85rem;
  font-weight: 700;
  text-transform: uppercase;
}

h1 {
  max-width: 14ch;
  margin: 0;
  font-size: clamp(2.5rem, 7vw, 5.5rem);
  line-height: 0.95;
}

p {
  max-width: 42rem;
  color: var(--muted);
  font-size: 1.05rem;
  line-height: 1.6;
}
`
    ],
    [
      path.join(appDir, 'src', 'data', 'fictional-recruitment-map-data.js'),
      `export const fictionalRecruitmentMapData = [
  {
    id: 'north-hub',
    label: 'North Hub',
    region: 'North',
    openRoles: 18,
    talentPool: 240,
    status: 'healthy'
  },
  {
    id: 'central-hub',
    label: 'Central Hub',
    region: 'Midlands',
    openRoles: 27,
    talentPool: 315,
    status: 'watch'
  },
  {
    id: 'south-hub',
    label: 'South Hub',
    region: 'South',
    openRoles: 14,
    talentPool: 205,
    status: 'healthy'
  }
];
`
    ],
    [
      path.join(appDir, 'src', 'lib', 'dom.js'),
      `export function clearElement(element) {
  while (element.firstChild) {
    element.removeChild(element.firstChild);
  }
}
`
    ],
    [
      path.join(appDir, 'src', 'features', 'recruitment-map', 'controller.js'),
      `export function createRecruitmentMapController({ data, view }) {
  return {
    init() {
      view.render(data);
    }
  };
}
`
    ],
    [
      path.join(appDir, 'src', 'features', 'recruitment-map', 'view.js'),
      `import { clearElement } from '../../lib/dom.js';

export function createRecruitmentMapView(root) {
  return {
    render(data) {
      clearElement(root);

      const section = document.createElement('section');
      section.className = 'empty-state';
      section.setAttribute('aria-labelledby', 'project-title');

      section.innerHTML = \`
        <p class="kicker">Fictional public demo data only</p>
        <h1 id="project-title">${answers.PROJECT_NAME}</h1>
        <p>Starter scaffold loaded with \${data.length} fictional recruitment regions.</p>
      \`;

      root.append(section);
    }
  };
}
`
    ],
    [
      path.join(appDir, 'tests', 'manual-test-plan.md'),
      `# Manual Test Plan

## Required Checks

- Confirm the demo loads locally with no console errors.
- Confirm all map information has a text or table alternative.
- Confirm keyboard users can reach every interactive control.
- Confirm reduced-motion preferences are respected.
- Confirm fictional-data labelling is visible.
- Confirm export behaviour, if implemented, does not include real data.
`
    ],
    [
      path.join(appDir, 'tests', 'accessibility-checklist.md'),
      `# Accessibility Checklist

- [ ] Page has one clear \`h1\`.
- [ ] Interactive controls have accessible names.
- [ ] Map regions are represented in an accessible list or table.
- [ ] Colour is not the only way to communicate status.
- [ ] Focus states are visible.
- [ ] Layout works at mobile and desktop widths.
- [ ] Reduced-motion mode avoids non-essential animation.
`
    ],
    [
      path.join(appDir, 'docs', 'agent-handoff.md'),
      `# Agent Handoff

## Current Stage

Governance intake complete. Implementation may proceed only inside the approved local demo scope after \`npm run governance:check\` passes.

## Approved Scope

${answers.APPROVAL_SCOPE}

## Conditions

${answers.APPROVAL_CONDITIONS}
`
    ],
    [
      path.join(appDir, 'docs', 'implementation-notes.md'),
      `# Implementation Notes

Record design decisions, assumptions, files changed, checks run and unresolved risks here as the local demo is implemented.
`
    ],
    [
      path.join(appDir, 'docs', 'review-evidence.md'),
      `# Review Evidence

Use this file to collect reviewer notes, accessibility evidence, security observations and test results before release approval.
`
    ],
    [
      path.join(appDir, '.gitkeep'),
      ''
    ]
  ]);

  let created = 0;
  for (const [file, content] of scaffoldFiles) {
    if (writeFileIfMissing(file, content)) created += 1;
  }
  return { created, slug };
}

const questions = JSON.parse(fs.readFileSync(questionsPath, 'utf8')).questions;
const rl = readline.createInterface({ input, output });
const answers = {};

console.log('\nAI-Agent SDLC governance intake');
console.log('Implementation is blocked until this intake is completed and human approval is recorded.\n');

for (const q of questions) {
  let answer = '';
  while (!hasValue(answer)) {
    const suffix = q.default ? ` [default: ${q.default}]` : '';
    answer = await rl.question(`${q.question}${suffix}: `);
    if (!hasValue(answer) && q.default) answer = q.default;
    answer = normalise(answer);
    if (q.allowed && hasValue(answer) && !q.allowed.includes(answer.toLowerCase())) {
      console.log(`Allowed values: ${q.allowed.join(', ')}`);
      answer = '';
    }
    if (q.required && !hasValue(answer)) {
      console.log('This answer is required.');
    }
  }
  answers[q.key] = answer;
}

answers.GENERATED_AT = new Date().toISOString();

ensureDir(path.dirname(answersPath));
ensureDir(outputDir);
fs.writeFileSync(answersPath, JSON.stringify(answers, null, 2));

for (const file of fs.readdirSync(templatesDir)) {
  if (!file.endsWith('.md')) continue;
  let content = fs.readFileSync(path.join(templatesDir, file), 'utf8');
  for (const [key, value] of Object.entries(answers)) {
    content = content.replaceAll(`[[${key}]]`, value);
  }
  fs.writeFileSync(path.join(outputDir, file), content);
}

const scaffold = createProjectScaffold(answers);

const status = {
  governance_initialized: true,
  approved_for_implementation: false,
  generated_at: answers.GENERATED_AT,
  project_slug: scaffold.slug,
  project_scaffold_files_created: scaffold.created,
  blocking_issues: ['Human approval is still required. Set APPROVED_FOR_IMPLEMENTATION: yes only after review.']
};
fs.writeFileSync(statusPath, JSON.stringify(status, null, 2));

await rl.close();

console.log('\nGovernance documents generated in docs/governance/.');
console.log(`Project scaffold ready in app/ (${scaffold.created} new files created).`);
console.log('STOP: human review is now required before implementation.');
console.log('After approval, update docs/governance/09-human-approval-record.md and run npm run governance:check.\n');
